/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import DAO.SecretariaDAO;
import Modelo.Secretaria;
import Modelo.Sessao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hermeson Alessandro
 */
public class Tela_excluir_secretaria extends javax.swing.JFrame {//Tela de exclusão da secretaria.
    
    /**
     * Creates new form Tela_excluir_secretaria
     */
    public Tela_excluir_secretaria() {
        initComponents();
        setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
        ListarSecretaria();
        jTable2.getSelectionModel().addListSelectionListener(event ->{
           if(!event.getValueIsAdjusting()){
               int selectedRow = jTable2.getSelectedRow();
               if(selectedRow != -1){
                  RgSelecionado = (String) jTable2.getValueAt(selectedRow, 0);
               }
           }
        });
    }
     
    public void setSaudacao(String saudacao, String dataHora) {
        jLabel2.setText(saudacao + " - " + dataHora);
    }
    /*
    Quando uma nova instância da tela Tela_excluir_secretaria é criada, ela inicializa todos os componentes da interface.
    Define uma saudação com a data e hora do login ativo do usuário.
    Lista todos as secretarias na tabela jtable2.
    Adiciona um ouvinte de eventos à tabela para monitorar a seleção de linhas.
    Quando uma linha é selecionada, o valor da primeira coluna da linha selecionada é armazena na variavel rgSelecionado.
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela_excluir_secretaria");
        setMinimumSize(new java.awt.Dimension(732, 674));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Excluir Secretaria(o)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 420, 70);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rg", "Nome", "D_nasc", "Sexo", "Endereço", "Telefone", "Email", "Senha", "Fk_cod_adm"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 700, 402);

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 520, 80, 40);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 520, 80, 40);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 610, 730, 16);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 770, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!RgSelecionado.equals("-1")){
            int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir uma secretaria(o)?", "Confirmaçao!", JOptionPane.YES_NO_OPTION);
            if(confirmacao == JOptionPane.YES_NO_OPTION){
                try{
                    SecretariaDAO dao = new SecretariaDAO();
                    dao.ExcluirSecretaria(RgSelecionado);
                    JOptionPane.showMessageDialog(null, "Secretaria(o) excluida com sucesso!");
                    if(Sessao.getRgUsuarioSec().equals(RgSelecionado)){
                        JOptionPane.showMessageDialog(null, "Voce se autoexcluiu e sera redirecionada para a tela de login!");
                        Sessao.LimparSessao();
                        Tela_login tl = new Tela_login();
                        tl.setVisible(true);
                        dispose();
                        return;
                    }
                    ListarSecretaria();
                    List<Secretaria> secretarias = dao.ListarSecretaria();
                    if(secretarias.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Nenhuma secretaria(o) restante, voce sera deslogada!");
                        Tela_login tl = new Tela_login();
                        tl.setVisible(true);
                        dispose();
                    }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "Erro ao excluir uma secretaria(o): " + e.getMessage());
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhuma secretaria(o) selecionada!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tela_ajuste_secretaria tas = new Tela_ajuste_secretaria();
        tas.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    /*
    O método verifica se uma secretaria foi selecionada.
    Solicita confirmação do usuário para a exclusão.
    Tenta excluir a secretaria e atualiza a lista de secretarias.
    Se a secretária exclúida for o usuário atualmente logado, limpa a sessão.
    Redireciona para a tela de login.
    O método trata possiveis erros e fornece feedback ao usuário em cada equipe do processo.
    */
        
    private void ListarSecretaria(){
        SecretariaDAO dao = new SecretariaDAO();
        List<Secretaria> secretarias = dao.ListarSecretaria();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        
        for(Secretaria secretaria : secretarias){
            model.addRow(new Object[]{
                secretaria.getRg(),
                secretaria.getNome(),
                secretaria.getD_nasc(),
                secretaria.getSexo(),
                secretaria.getEndereco(),
                secretaria.getTelefone(),
                secretaria.getEmail(),
                secretaria.getSenha(),
                secretaria.getFk_cod_adm(),
            });
        }
    }
    /*
    O método de ListarSecretaria é utilizado para preencher a tabela jTable2 com os dados de todas as secretarias.
    Ele obtém a lista de secretárias do banco de dados.
    Limpa a tabela e adiciona uma nova linha para cada secretaria na lista.
    A variável Rgselecionado é usada para armazenar o rg da secretaria atualmente selecionada na tabela.
    */
    
    private String RgSelecionado = "-1";//Variável de instância.
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_excluir_secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
