/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import DAO.SecretariaDAO;
import Modelo.Secretaria;
import Modelo.Sessao;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hermeson Alessandro
 */
public class Tela_alterar_secretaria extends javax.swing.JFrame {//Atualiza, carrega e limpa os Campos.
private Secretaria secretaria;

    /**
     * Creates new form Tela_alterar_secretaria
     */
    public Tela_alterar_secretaria() {
        initComponents();
    }

    public Tela_alterar_secretaria(Secretaria secretaria){
        initComponents();
        this.secretaria = secretaria;
        PreencherCampos();
        setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
    }
    
    public void setSaudacao(String saudacao, String dataHora) {
        jLabel11.setText(saudacao + " - " + dataHora);
    }
    /*
    Tela_alterar_secretaria é instanciada.
    Ela inicializa seus componentes, armazena a secretaria passada como parametro.
    Preenche os campos da interface com as informações dessa secretaria.
    Define uma saudação que inclui a data e hora do login ativo.
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela_alterar_secretaria");
        setMinimumSize(new java.awt.Dimension(725, 674));
        setPreferredSize(new java.awt.Dimension(725, 640));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Alterar Secretaria(o)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 430, 64);

        jLabel2.setText("Rg");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 110, 30, 16);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(190, 110, 400, 22);

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 150, 33, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 150, 390, 22);

        jLabel4.setText("D_nasc");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 190, 50, 16);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 190, 380, 22);

        jLabel5.setText("Sexo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 230, 40, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "Outros", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(200, 230, 72, 22);

        jLabel6.setText("Endereço");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 270, 70, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 270, 360, 22);

        jLabel7.setText("Telefone");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 310, 60, 16);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 310, 370, 22);

        jLabel8.setText("Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 350, 40, 16);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 350, 390, 22);

        jLabel9.setText("Senha");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 390, 50, 16);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 390, 380, 22);

        jLabel10.setText("Fk_cod_adm");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 430, 80, 16);

        jTextField8.setEditable(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(240, 430, 350, 22);

        jButton1.setText("Alterar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 500, 72, 40);

        jButton2.setText("Limpar Campos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 500, 130, 40);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 500, 110, 40);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 610, 710, 16);

        jLabel12.setBackground(new java.awt.Color(0, 255, 255));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 750, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty()
            || jTextField4.getText().isEmpty() || jComboBox1.getSelectedItem() == null
            || jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty() ||
            jTextField7.getText().isEmpty() || jPasswordField2.getPassword().length == 0
            || jTextField8.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos vazios, por favor preencher todos os campos!");
        }else{
            try{
                String telefone = jTextField6.getText();
                if(!telefone.matches("\\d+")){
                    throw new NumberFormatException("Numero deve conter apenas digitos!");
                }//Verifica a String informando que só pode ter dígitos.
                if(telefone.length() != 11){
                    throw new IllegalArgumentException("Numero deve conter exatamente 11 dígitos");
                }//Numero deve ter apenas 11 dígitos.
                String datatexto = jTextField4.getText();
                if (datatexto.isEmpty()) {
                    throw new DateTimeParseException("Data vazia!", datatexto, 0);
                }//Faz a verificação da data para ver se esta vazia.

                if(datatexto.matches("\\d{8}")){
                    datatexto = datatexto.substring(0, 2) + "/" + datatexto.substring(2, 4) + "/" + datatexto.substring(4, 8);
                }
                /*
                Verifica se a string datatexto tem exatamente 8 dígitos.
                Se a verificação for bem-sucedida, formata a string para o formato de data "dd/MM/yyyy".
                */

                String rg = jTextField2.getText();
                if(!rg.matches("\\d{11}") && !rg.matches("\\d{10}-\\d")){
                    throw new IllegalArgumentException("Rg deve ser no formato 99999999999 ou 9999999999-9!");
                }

                rg = rg.replace("-", "");
                /*
                A entrada do campo de texto jTextField2 contenha um RG no formato de 11 dígitos consecutivos ou 10 dígitos seguidos por um hífen e mais um dígito.
                Se a validação falhar, lança uma exceção informando o formato correto.
                Se a validação for bem-sucedida e houver um hífen no RG, ele é removido.
                */

                DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate datanascimento = LocalDate.parse(datatexto,formatar);
                //O DateTimeFormatter está configurado para interpretar essa string no formato "dd/MM/yyyy".

                Secretaria secretaria = new Secretaria();
                secretaria.setRg(jTextField2.getText());
                secretaria.setNome(jTextField3.getText());
                secretaria.setD_nasc(datanascimento);
                secretaria.setSexo(jComboBox1.getSelectedItem().toString());
                secretaria.setEndereco(jTextField5.getText());
                secretaria.setTelefone(Long.parseLong(telefone));
                secretaria.setEmail(jTextField7.getText());
                secretaria.setSenha(new String(jPasswordField2.getPassword()));
                secretaria.setFk_cod_adm(Integer.parseInt(jTextField8.getText()));

                SecretariaDAO dao = new SecretariaDAO();
                dao.AlterarSecretaria(secretaria);
                JOptionPane.showMessageDialog(null, "Secretaria(o) atualizada com sucesso!");
                Tela_ajuste_secretaria tas = new Tela_ajuste_secretaria();
                tas.setVisible(true);
                dispose();
            }catch(NumberFormatException e ){
                JOptionPane.showMessageDialog(null, "Erro de formataçao: " +e.getMessage());
            }catch(DateTimeParseException e){
                JOptionPane.showMessageDialog(null, "Erro de formataçao da data: " +e.getMessage());
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro ao atualizar a secretaria(o): " +e.getMessage());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro inesperado: " +e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jComboBox1.setSelectedItem(0);
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jPasswordField2.setText("");
        jTextField8.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tela_ajuste_secretaria tas = new Tela_ajuste_secretaria();
        tas.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    /*
    Esse método é responsável por realizar a limpeza dos campos.
    Ou seja aonde tiver String vai ser substituida por "" e aonde tiver inteiro vai ser 0 ou seja nada.
    */
        /*
    Em resumo esse método verifica se todos os campos obrigatórios estão preenchidos.
    Se estiverem ele valida e formata os dados.
    Cria uma instância da Secretaria.
    Define seus atributos.
    Atualiza as informações no banco de dados.
    Fornece feedbacks ao usuário.
    Tratando eventuias erros que possam ocorrer durante o processo.
    */
        
    private void PreencherCampos(){
        DateTimeFormatter formatar = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        jTextField2.setText(String.valueOf(secretaria.getRg()));
        jTextField3.setText(secretaria.getNome());
        jTextField4.setText(secretaria.getD_nasc().format(formatar));
        jComboBox1.setSelectedItem(secretaria.getSexo());
        jTextField5.setText(secretaria.getEndereco());
        jTextField6.setText(String.valueOf(secretaria.getTelefone()));
        jTextField7.setText(secretaria.getEmail());
        jPasswordField2.setText(secretaria.getSenha());
        jTextField8.setText(String.valueOf(secretaria.getFk_cod_adm()));
    }
    /*
    O metodo de PreencherCampos é reponsável por preencher os campos da interface gráfica com os dados da secretaria.
    Permitindo que o usuario visualize, edite, as informações da secretaria.
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_alterar_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_alterar_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_alterar_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_alterar_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_alterar_secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
