/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import Modelo.Secretaria;
import DAO.SecretariaDAO;
import Visao.Tela_ajuste_secretaria;
import Modelo.Sessao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hermeson Alessandro
 */
public class Tela_ajuste_secretaria extends javax.swing.JFrame {////Tela para cuidar dos ajustes da secretaria.

    /**
     * Creates new form Tela_ajuste_secretaria
     */
    public Tela_ajuste_secretaria() {
        initComponents();
        ListarSecretaria();
        setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
    }
    
    public void setSaudacao(String saudacao, String dataHora) {
        jLabel4.setText(saudacao + " - " + dataHora);
    }
    /*
    Quando a tela Tela_ajuste_secretaria é instânciada.
    Ela inicializa seus componentes, lista as secretarias e define uma saudação que inclui a data e hora do login ativo.
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela_ajuste_secretaria");
        setMinimumSize(new java.awt.Dimension(749, 597));
        setPreferredSize(new java.awt.Dimension(749, 696));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Secretarias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 230, 64);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Rg", "Nome", "D_nasc", "Sexo", "Endereço", "Telefone", "Email", "Senha", "Fk_cod_adm"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 720, 402);

        jLabel2.setText("Para alterar secretaria vá para a aba chamada \"Alterar\" em seguida clique em \"Alterar/SEC\"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 500, 510, 16);

        jLabel3.setText("Para excluir secretaria vá para a aba chamada \"Excluir\" em seguida clique em \"Excluir/SEC\"");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 520, 520, 16);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 560, 80, 40);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 610, 740, 16);

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 750, 690);

        jMenu1.setText("Alterar");

        jMenuItem1.setText("Alterar/SEC");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Excluir");

        jMenuItem2.setText("Excluir/SEC");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(SecretariaSelecionada != null){
            Tela_alterar_secretaria tas = new Tela_alterar_secretaria(SecretariaSelecionada);
            tas.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma secretaria(o) para alterar!");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /*
    Quando o item de menu é clicado, o código verifica se uma secreataria está selecionada.
    Se estiver, abre uma nova tela (Tela_alterar_secretaria) com a secretaria selecionada e fecha a janela atual.
    Se não houver uma secretaria selecionada, exibe uma mensagem de alerta para o usuário.
    */
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tela_excluir_secretaria tes = new Tela_excluir_secretaria();
        tes.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow != -1){
            String rg = (String) jTable1.getValueAt(selectedRow, 0);
            SecretariaDAO dao = new SecretariaDAO();
            SecretariaSelecionada = dao.BuscarSecretariaPorRg(rg);
            if(SecretariaSelecionada != null){
                JOptionPane.showMessageDialog(null, "Secretaria(o) selecionada: "+SecretariaSelecionada.getNome());
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao selecionar a secretaria(o)!");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tela_inicial_secretaria tis = new Tela_inicial_secretaria();
        tis.setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
        tis.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    Este código busca uma secretaria selecionada em uma tabela (jTable1). Ele obtém o
    código da secretaria da linha selecionada, usa esse código para buscar o
    secretaria no banco de dados, e exibe uma mensagem com o nome da secretaria,
    caso encontrado. Se nenhuma secretaria for encontrada, exibe uma mensagem de erro.
    */
    
    private Secretaria SecretariaSelecionada;
    private void ListarSecretaria(){
        SecretariaDAO dao = new SecretariaDAO();
        List<Secretaria> secretarias = dao.ListarSecretaria();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        for(Secretaria secretaria : secretarias){
            model.addRow(new Object[]{
                secretaria.getRg(),
                secretaria.getNome(),
                secretaria.getD_nasc(),
                secretaria.getSexo(),
                secretaria.getEndereco(),
                secretaria.getTelefone(),
                secretaria.getEmail(),
                secretaria.getSenha(),
                secretaria.getFk_cod_adm(),
            });
        }
    }
    
    /*
    O método ListarSecretaria busca uma lista de secretarias do banco de dados
    usando SecretariaDAO, limpa a tabela jTable1 e preenche-a com os dados das
    secretarias. Cada secretaria é adicionada à tabela como uma nova linha com
    suas informações.
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_ajuste_secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
