/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import DAO.BebidaDAO;
import Modelo.Bebida;
import Modelo.Sessao;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Locale;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Hermeson Alessandro
 */
public class Tela_cadastrar_bebida extends javax.swing.JFrame {//Tela de Cadastro do administrador.

    /**
     * Creates new form Tela_cadastrar_bebida
     */
    public Tela_cadastrar_bebida() {
        initComponents();
        setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
    }
    
    public void setSaudacao(String saudacao, String dataHora) {
        jLabel9.setText(saudacao + " - " + dataHora);
    }
    /*
    Quando a nova instância da Tela_cadastrar_bebida é criada, ela inicializa todos os componentes da interface.
    Define uma mensagem de saudação com a data e hora do login ativo do usuário.
    O metodo setSaudacao é usada para formatar e definir essa mensagem no componentes jlabel9.
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela_cadastrar_bebida");
        setMinimumSize(new java.awt.Dimension(737, 603));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Cadastrar Bebida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 30, 360, 64);

        jLabel2.setText("Cod");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 120, 30, 16);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 120, 390, 22);

        jLabel3.setText("Descriçao");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 160, 60, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 160, 370, 22);

        jLabel4.setText("Marca");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 200, 40, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 200, 380, 22);

        jLabel5.setText("Gp_mercadoria");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 240, 90, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebidas Fermentadas", "Bebidas Destiladas", "Licores e Outras Bebidas", "Coquetéis e Drinks" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(260, 240, 162, 22);

        jLabel6.setText("T_de_item");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 280, 70, 16);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direto ao Cliente", "Revenda" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(230, 280, 130, 22);

        jLabel7.setText("Q_estoque");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 320, 70, 16);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(240, 320, 350, 22);

        jLabel8.setText("V_unitário");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 360, 70, 16);

        jTextField5.setText("R$ ");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(230, 360, 360, 22);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 450, 90, 40);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 450, 90, 40);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 540, 720, 16);

        jLabel10.setBackground(new java.awt.Color(0, 255, 255));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 750, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() ||
            jComboBox1.getSelectedItem() == null || jComboBox2.getSelectedItem() == null ||
            jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos vazios, por favor preencher todos os campos!");
        }else{
            Bebida bebida = new Bebida();
            bebida.setDescricao(jTextField2.getText());
            bebida.setMarca(jTextField3.getText());
            bebida.setGp_mercadoria(jComboBox1.getSelectedItem().toString());
            bebida.setT_do_item(jComboBox2.getSelectedItem().toString());
            bebida.setQ_estoque(Integer.parseInt(jTextField4.getText()));

            String valorUnitarioStr = jTextField5.getText().replace("R$", "").trim().replace(",", ".");
            NumberFormat nf = NumberFormat.getInstance(Locale.US);
            //Capturar e formatar um valor monetário, removendo o símbolo de moeda e ajustando o formato de decimal.
            //Criar um formatador numérico que segue as convenções dos Estados Unidos, permitindo manipulação e conversão consistentes de números.

            try{
                Number number = nf.parse(valorUnitarioStr);
                bebida.setV_unitario(number.doubleValue());
                /*
                Usa o NumberFormat para converter uma string formatada (valorUnitarioStr) em um objeto Number.
                Converte o objeto Number para um tipo primitivo double.
                Define o valor unitário (v_unitario) do objeto bebida com o valor convertido.
                */
            }catch(ParseException e){
                JOptionPane.showMessageDialog(null, "Erro ao formatar o valor unitario da bebida: " +e.getMessage());
                return;
            }

            String CodigodeBarras = GerarCodigodeBarras();
            bebida.setCod_de_barras(CodigodeBarras);
            //Usado para gerar um código de barras.

            try{
                BebidaDAO dao = new BebidaDAO();
                if(dao.DescricaoExiste(bebida.getDescricao())){
                    JOptionPane.showMessageDialog(null, "Descricao da bebida ja existe. Tente novamente!");
                }else{
                    dao.CadastrarBebida(bebida);
                    JOptionPane.showMessageDialog(null, "Bebida cadastrada com sucesso! codigo de barras gerado: " + CodigodeBarras);
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar uma bebida: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Tela_inicial_secretaria tis = new Tela_inicial_secretaria();
        tis.setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
        tis.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    /*
    Esse método verifica se todos os campos estão preenchidos.
    Cria um objeto Bebida com os valores fornecidos.
    Formata o valor unitario.
    Gera um codigo de barras.
    Tenta cadastrar a nova bebida no banco de dados.
    Se tudo ocorrer bem, exibe uma mensagem de sucesso. Caso contrario, trata os erros adequadamente fornecendo feedback ao usuario.
    */
    
    private String GerarCodigodeBarras(){
        Random random = new Random();
        StringBuilder CodigodeBarras = new StringBuilder();
        for(int i = 0; i < 13; i++){
            int cod_digito = random.nextInt(10);
            CodigodeBarras.append(cod_digito);
        }
        return CodigodeBarras.toString();
    }
    /*
    Em resumo esse metodo gera um código de barras de 13 digitos.
    Onde cada digito é um numero aleatório entre 0 a 9.
    Esse código é construido utilizando um StringBuilder e ao final em uma String e retornado.
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastrar_bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastrar_bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastrar_bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastrar_bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastrar_bebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
