/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import DAO.ClienteDAO;
import Modelo.Cliente;
import Modelo.Sessao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hermeson Alessandro
 */
public class Tela_ajuste_cliente extends javax.swing.JFrame {//Tela para cuidar dos ajustes do cliente.

    /**
     * Creates new form Tela_ajuste_cliente
     */
    public Tela_ajuste_cliente() {
        initComponents();
        ListarCliente();
        setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
    }
    
    public void setSaudacao(String saudacao, String dataHora) {
        jLabel4.setText(saudacao + " - " + dataHora);
    }
    /*
    Quando a tela Tela_ajuste_cliente é instânciada.
    Ela inicializa seus componentes, lista os clientes e define uma saudação que inclui a data e hora do login ativo.
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela_ajuste_cliente");
        setMinimumSize(new java.awt.Dimension(760, 685));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 0, 167, 64);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cpf", "Nome", "D_nasc", "Sexo", "Endereço", "Telefone", "Email", "Senha", "Fk_rg_sec"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 720, 402);

        jLabel2.setText("Para alterar cliente vá para a aba chamada \"Alterar\" em seguida clique em \"Alterar/CLI\"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 490, 500, 16);

        jLabel3.setText("Para excluir cliente vá para a aba chamada \"Excluir\" em seguida clique em \"Excluir/CLI\"");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 510, 500, 16);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 540, 80, 40);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 600, 750, 16);

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -10, 770, 680);

        jMenu1.setText("Alterar");

        jMenuItem1.setText("Alterar/CLI");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Excluir");

        jMenuItem2.setText("Excluir/CLI");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(ClienteSelecionado != null){
            Tela_alterar_cliente tac = new Tela_alterar_cliente(ClienteSelecionado);
            tac.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecione um cliente para alterar!");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /*
    Quando o item de menu é clicado, o código verifica se um cliente está selecionado.
    Se estiver, abre uma nova tela (Tela_alterar_cliente) com o cliente selecionado e fecha a janela atual.
    Se não houver um cliente selecionado, exibe uma mensagem de alerta para o usuário.
    */
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Tela_excluir_cliente tec = new Tela_excluir_cliente();
        tec.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow != -1){
            String cpf = (String) jTable1.getValueAt(selectedRow, 0);
            ClienteDAO dao = new ClienteDAO();
            ClienteSelecionado = dao.BuscarClientePorCpf(cpf);
            if(ClienteSelecionado != null){
                JOptionPane.showMessageDialog(null, "Cliente selecionado: "+ClienteSelecionado.getNome());
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao selecionar o cliente!");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tela_inicial_cliente tic = new Tela_inicial_cliente();
        tic.setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
        tic.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    Este código busca um cliente selecionado em uma tabela (jTable1). Ele obtém o
    código do cliente da linha selecionada, usa esse código para buscar o
    cliente no banco de dados, e exibe uma mensagem com o nome do cliente,
    caso encontrado. Se nenhum cliente for encontrado, exibe uma mensagem de erro.
    */
    
    private Cliente ClienteSelecionado;
    private void ListarCliente(){
        ClienteDAO dao = new ClienteDAO();
        List<Cliente> clientes = dao.ListarCliente();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        
        for(Cliente cliente : clientes){
            model.addRow(new Object[]{
                cliente.getCpf(),
                cliente.getNome(),
                cliente.getD_nasc(),
                cliente.getSexo(),
                cliente.getEndereco(),
                cliente.getTelefone(),
                cliente.getEmail(),
                cliente.getSenha(),
                cliente.getFk_rg_sec(),
            });
        }
    }
    /*
    O método ListarCliente busca uma lista de clientes do banco de dados
    usando ClienteDAO, limpa a tabela jTable1 e preenche-a com os dados dos
    clientes. Cada cliente é adicionado à tabela como uma nova linha com
    suas informações.
    */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_ajuste_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_ajuste_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
