/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;
import DAO.PedidoDAO;
import Modelo.Bebida;
import Modelo.Cliente;
import Modelo.Pedido;
import Modelo.Sessao;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Hermeson Alessandro
 */
public class Tela_confirmacao_pedido extends javax.swing.JFrame {//Tela de confirmação da bebida.
private Cliente cliente;
private Bebida bebida;

    /**
     * Creates new form Tela_confirmacao_pedido
     */
    public Tela_confirmacao_pedido() {
        initComponents();
    }
    
    public Tela_confirmacao_pedido(Cliente cliente, Bebida bebida){
        initComponents();
        this.cliente = cliente;
        this.bebida = bebida;
        PreencherCamposCliente();
        PreencherCamposBebida();
        setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
    }
    
    public void setSaudacao(String saudacao, String dataHora) {
        jLabel17.setText(saudacao + " - " + dataHora);
    }
    /*
    Quando uma nova instância da tela Tela_confirmacao_pedido é criada ela inicializa todos os componentes da interface.
    Armazena os objetos Cliente e Bebida.
    Preenche os campos da interface com as informações desses objetos.
    E define uma mensagem de saudação com  a data e hora do login ativo do usuário.
    O metodo setSaudacao é utilizado para formatar e definir essa mensagem no componente jlabel17.
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela_confirmacao_pedido");
        setMinimumSize(new java.awt.Dimension(1056, 584));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Confirmação do Pedido");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 510, 64);

        jLabel2.setText("Cpf do cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 110, 90, 16);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 110, 310, 22);

        jLabel3.setText("Nome do cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 110, 100, 16);

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(650, 110, 330, 22);

        jLabel4.setText("Endereço do cliente");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 150, 120, 16);

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 150, 280, 22);

        jLabel5.setText("Telefone do cliente");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 150, 120, 16);

        jTextField4.setEditable(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(670, 150, 310, 22);

        jLabel6.setText("Email do cliente");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 190, 110, 16);

        jTextField5.setEditable(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(170, 190, 310, 22);

        jLabel7.setText("Descrição da bebida");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 190, 120, 16);

        jTextField6.setEditable(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(680, 190, 300, 22);

        jLabel8.setText("Codigo de barras da bebida");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 230, 160, 16);

        jTextField7.setEditable(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(240, 230, 240, 22);

        jLabel9.setText("Marca da bebida");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(550, 230, 130, 16);

        jTextField8.setEditable(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(650, 230, 330, 22);

        jLabel10.setText("Gp de mercadoria da bebida");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 270, 170, 16);

        jTextField9.setEditable(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(240, 270, 240, 22);

        jLabel11.setText("Tipo de item da bebida");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(550, 270, 140, 16);

        jTextField10.setEditable(false);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(690, 270, 290, 22);

        jLabel12.setText("Q_estoque da bebida");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 310, 140, 16);

        jTextField11.setEditable(false);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(200, 310, 280, 22);

        jLabel13.setText("Q_adquirida para pedido");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(550, 310, 150, 16);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(700, 310, 280, 22);

        jLabel14.setText("V_unitario da bebida");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 350, 120, 16);

        jTextField13.setEditable(false);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(200, 350, 280, 22);

        jLabel16.setText("Codigo da bebida");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(550, 350, 120, 16);

        jTextField14.setEditable(false);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(660, 350, 320, 22);

        jButton1.setText("Confirmar pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 430, 150, 50);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 430, 90, 50);

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(670, 430, 90, 50);

        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 520, 1050, 16);

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Sistema_Funcional_de_Bebidas\\Sistema_Funcional_de_Bebidas\\Sistema_Funcional_de_Bebidas\\src\\main\\java\\Imagem\\Fundo Confirmacao Pedido 1100-600.png")); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1060, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jTextField3.getText().isEmpty() ||
            jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty() || jTextField6.getText().isEmpty() ||
            jTextField8.getText().isEmpty() || jTextField9.getText().isEmpty() || jTextField10.getText().isEmpty() ||
            jTextField11.getText().isEmpty() || jTextField12.getText().isEmpty() || jTextField13.getText().isEmpty() ||
            jTextField14.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos vazios, por favor preencher todos os campos!");
        }else{
            Cliente cliente = new Cliente();
            cliente.setCpf(jTextField1.getText());
            cliente.setNome(jTextField2.getText());
            cliente.setEndereco(jTextField3.getText());
            cliente.setTelefone(Long.parseLong(jTextField4.getText()));
            cliente.setEmail(jTextField5.getText());

            Bebida bebida = new Bebida();
            bebida.setDescricao(jTextField6.getText());
            bebida.setCod_de_barras(jTextField7.getText());
            bebida.setMarca(jTextField8.getText());
            bebida.setGp_mercadoria(jTextField9.getText());
            bebida.setT_do_item(jTextField10.getText());
            int qEstoque = Integer.parseInt(jTextField11.getText());
            bebida.setQ_estoque(qEstoque);
            bebida.setV_unitario(Double.parseDouble(jTextField13.getText().replace(",", ".")));
            bebida.setCod(Integer.parseInt(jTextField14.getText()));
            //Capturar e formatar um valor monetário, removendo o símbolo de moeda e ajustando o formato de decimal.
            //Criar um formatador numérico que segue as convenções dos Estados Unidos, permitindo manipulação e conversão consistentes de números.

            int quantidade = Integer.parseInt(jTextField12.getText());
            if(quantidade > qEstoque){
                JOptionPane.showMessageDialog(null, "Quantidade insuficiente em estoque!");
                return;
            }
            double valorUnitario = bebida.getV_unitario();
            double valorTotal = quantidade * valorUnitario;

            Pedido pedido = new Pedido();
            pedido.setFk_cpf_cliente(cliente.getCpf());
            pedido.setNome_cliente(cliente.getNome());
            pedido.setEndereco_cliente(cliente.getEndereco());
            pedido.setTelefone_cliente(cliente.getTelefone());
            pedido.setEmail_cliente(cliente.getEmail());
            pedido.setDescricao_bebida(bebida.getDescricao());
            pedido.setCod_de_barras_bebida(bebida.getCod_de_barras());
            pedido.setMarca_bebida(bebida.getMarca());
            pedido.setGp_mercadoria_bebida(bebida.getGp_mercadoria());
            pedido.setT_do_item_bebida(bebida.getT_do_item());
            pedido.setQ_estoque_bebida(bebida.getQ_estoque());
            pedido.setQ_adquirida_do_pedido(quantidade);
            pedido.setV_unitario_bebida(valorUnitario);
            pedido.setV_total_pedido(valorTotal);
            pedido.setFk_cod_bebida(bebida.getCod());

            try{
                PedidoDAO dao = new PedidoDAO();
                dao.CadastrarPedido(pedido);
                bebida.setQ_estoque(bebida.getQ_estoque() - quantidade);
                dao.AtualizarEstoque(bebida);

                if(bebida.getQ_estoque() == 0){
                    jButton1.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "Produto esgotado!");
                }

                int pedidoId = pedido.getId();
                JOptionPane.showMessageDialog(null, "Valor Total: " + String.format("%.2f", valorTotal));//Faz a formatação em duas casas decimais.
                Tela_caixa tc = new Tela_caixa(pedidoId);
                tc.setVisible(true);
                dispose();
            }catch(SQLException e ){
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar o pedido: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "Pedido cancelado, Voltando para o menu do cliente!");
        Tela_inicial_cliente tic = new Tela_inicial_cliente();
        tic.setSaudacao("Login ativo desde:", Sessao.getDataHoraEntrada());
        tic.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Tela_comprar_bebida tcb = new Tela_comprar_bebida();
        tcb.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    /*
    O método jButton1ActionPerformed verifica se todos os campos estão preenchidos e se
    a quantidade desejada está disponível em estoque. Se essas condições forem satisfeitas,
    ele cria instâncias dos objetos Cliente, Bebida e Pedido, e realiza o cadastro do
    pedido no banco de dados, atualizando o estoque da bebida. Se o estoque se esgotar,
    desabilita o botão jButton1 e exibe uma mensagem informando que o produto está
    esgotado. Em caso de erro, exibe uma mensagem de erro apropriada.
    */ 
        
    private void PreencherCamposCliente(){
        jTextField1.setText(String.valueOf(cliente.getCpf()));
        jTextField2.setText(cliente.getNome());
        jTextField3.setText(cliente.getEndereco());
        jTextField4.setText(String.valueOf(cliente.getTelefone()));
        jTextField5.setText(cliente.getEmail());
    }
    /*
    O método de PreencherCamposCliente pega os dados do objeto Cliente e os insere nos campos da interface.
    Permite que o usuario visualize e, se necessario, edite as informações do cliente.
    Cada campo da interface é preenchido com valor correspondente do objeto Cliente.
    */
    
    private void PreencherCamposBebida(){
        DecimalFormat df = new DecimalFormat("#.00");
        jTextField6.setText(bebida.getDescricao());
        jTextField7.setText(bebida.getCod_de_barras());
        jTextField8.setText(bebida.getMarca());
        jTextField9.setText(bebida.getGp_mercadoria());
        jTextField10.setText(bebida.getT_do_item());
        jTextField11.setText(String.valueOf(bebida.getQ_estoque()));
        jTextField13.setText(df.format(bebida.getV_unitario()));
        jTextField14.setText(String.valueOf(bebida.getCod()));
    }
    /*
    O metodo de preencherCamposBebidas é utilizado para preencher os campos da interface com os dados da bebida.
    Permite ao usuário visualizar e se, necessário, editar essas informações.
    Cada campo da interface é preenchido com o valor correspondente do objeto Bebida.
    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_confirmacao_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_confirmacao_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_confirmacao_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_confirmacao_pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_confirmacao_pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
